name: github pages

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
        with:
          components: rustfmt

      - name: Cache binaries
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-bin-${{ hashFiles('.github/workflows/build.sh') }}
          restore-keys: |
            ${{ runner.os }}-bin-

      - name: Build
        run: .github/workflows/build.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html

  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
        with:
          components: rustfmt

      - name: Cache binaries
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-bin-${{ hashFiles('.github/workflows/build.sh') }}
          restore-keys: |
            ${{ runner.os }}-bin-

      - name: Build
        run: CHECK=1 .github/workflows/build.sh
