name: github pages

on:
  push:
    branches:
      - main
      - test
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # stable
        with:
          components: rustfmt

      - name: Cache binaries
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-bin-${{ hashFiles('.github/workflows/build.sh') }}
          restore-keys: |
            ${{ runner.os }}-bin-

      - name: Build
        run: .github/workflows/build.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@e9c66a37f080288a11235e32cbe2dc5fb3a679cc # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html

  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # stable
        with:
          components: rustfmt

      - name: Cache binaries
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-bin-${{ hashFiles('.github/workflows/build.sh') }}
          restore-keys: |
            ${{ runner.os }}-bin-

      - name: Build
        run: CHECK=1 .github/workflows/build.sh
